# ---- Data sources ----
D_values_path: "data/D_values.csv"

# ---- FPHS anchors ----
lattice_sizes: [8, 12]
inverse_couplings: [3.0, 3.5]
pivot_slopes: [0.75, 1.0]
gauge_groups: ["SU2", "SU3"]

# ---- Measurement schedules & f-grid ----
f_grid:
  during: [0.0, 0.05, 0.10, 0.20, 0.30, 0.50]
  pre:    [0.0, 0.30]
  post:   [0.0, 0.30]

seeds: [0, 1, 2, 3, 4]

pivot:
  logistic_n0: 0.0

# ---- Measurement (HYBRID) ----
measurement:
  selection: "uniform"
  kick_passes: 3          # amplify the dephasing per snapshot/cycle

# ---- Visibility ----
visibility:
  num_phi: 64
  cycles: 8
  eps: 1.0e-12
  eps_scale: 1.0e-6

# ---- Wilson loops / Creutz ----
loops:
  creutz_sizes: [[2, 2]]
  block_size: 64
  min_valid_fraction: 0.95
  measurement_cycles: 4   # average Ïƒ & P over measured snapshots when schedule='during'

# ---- Analysis ----
analysis:
  r2_min: 0.80
  monotonicity_confidence: 0.95
